# Chapter 1 playground

In [2]:
using Statistics

@time begin
    data = Float64[]
    for _ in 1:10^6
        group = []
        for _ in 1:5*10^2
            push!(group, rand())
        end
        push!(data, mean(group))
    end
    println("98% of the means lie in the estimated range: ", 
        (quantile(data, 0.01), quantile(data, 0.99))
    )
end

98% of the means lie in the estimated range: (0.4699332202453785, 0.5300549883940808)
 21.171818 seconds (1.51 G allocations: 30.341 GiB, 4.68% gc time)


In [3]:
using Statistics

@time begin
    data = [mean(rand(5*10^2)) for _ in 1:10^6]
        println("98% of the means lie in the estimated range: ", 
        (quantile(data, 0.01), quantile(data, 0.99))
    )
end

98% of the means lie in the estimated range: (0.469973846509801, 0.5299652147164318)
  1.673241 seconds (1.27 M allocations: 3.912 GiB, 40.05% gc time, 5.32% compilation time)


## Takeaways
- The `!` in `push!(collection, element)` means this function mutates the argument
- List comprehensions are faster
- Compare to python

```python
%%time   

data = []
for _ in range(1, 10**6):
    group = []
    for _ in range(1, 5*10**2):
        group.append(random.random())
    data.append(mean(group))
               
print("98% of the means lie in the estimated range: ", 
          (np.quantile(data, .01), np.quantile(data, .99)))
```

produces 

98% of the means lie in the estimated range:  (0.469880247744724, 0.5301088536142381)

CPU times: user 51.6 s, sys: 35.2 ms, total: 51.6 s

Wall time: 51.6 s

## Multiple Dispatch is runtime method overloading
- Julia engages in type inference whenever possible, but w/ multiple dispatch, we can control the behavior
- Multiple dispatch also works w/ user defined types

In [11]:
function foo(x)::Int64
    return x + 1
end

foo (generic function with 1 method)

In [12]:
function foo(x)::Float64
    return x - 1
end

foo (generic function with 1 method)

In [13]:
foo(2)

1.0

In [14]:
foo(2.3)

1.2999999999999998

In [18]:
?supertypes

search: supertypes supertype



```
supertypes(T::Type)
```

Return a tuple `(T, ..., Any)` of `T` and all its supertypes, as determined by successive calls to the [`supertype`](@ref) function, listed in order of `<:` and terminated by `Any`.

# Examples

```jldoctest
julia> supertypes(Int)
(Int64, Signed, Integer, Real, Number, Any)
```


In [19]:
?subtypes

search: subtypes



```
subtypes(T::DataType)
```

Return a list of immediate subtypes of DataType `T`. Note that all currently loaded subtypes are included, including those not visible in the current module.

# Examples

```jldoctest
julia> subtypes(Integer)
3-element Vector{Any}:
 Bool
 Signed
 Unsigned
```


In [20]:
subtypes(Integer)

3-element Vector{Any}:
 Bool
 Signed
 Unsigned

In [21]:
supertypes(Integer)

(Integer, Real, Number, Any)

In [22]:
subtypes(Number)

2-element Vector{Any}:
 Complex
 Real

In [23]:
supertypes(Number)

(Number, Any)

In [24]:
supertypes(Any)

(Any,)

In [25]:
subtypes(Any)

560-element Vector{Any}:
 AbstractArray
 AbstractChannel
 AbstractChar
 AbstractDict
 AbstractDisplay
 AbstractMatch
 AbstractPattern
 AbstractSet
 AbstractString
 Any
 Base.AbstractBroadcasted
 Base.AbstractCartesianIndex
 Base.AbstractCmd
 ⋮
 Tuple
 Type
 TypeVar
 UndefInitializer
 Val
 Vararg
 VecElement
 VersionNumber
 WeakRef
 ZMQ.Context
 ZMQ.Socket
 ZMQ._Message